import { ActivityType, Habit, Periodicity, GoalType, Target, TargetType } from '~/types/types';

const targets: Target[] = [
    {
        id: '1',
        date: new Date('2023-12-01'),
        createDate: new Date(),
        targetType: TargetType.Done,
    },
    {
        id: '2',
        date: new Date('2023-12-02'),
        createDate: new Date(),
        targetType: TargetType.Done,
    },
    {
        id: '3',
        date: new Date('2023-12-03'),
        createDate: new Date(),
        targetType: TargetType.Skip,
    },
    {
        id: '4',
        date: new Date('2023-12-04'),
        createDate: new Date(),
        targetType: TargetType.Done,
    },
    {
        id: '5',
        date: new Date('2023-12-05'),
        createDate: new Date(),
        targetType: TargetType.Done,
    },
];

export const habits: Habit[] = [
    {
        id: '1',
        title: 'Meditate',
        periodicity: Periodicity.Daily,
        activityType: ActivityType.Counter,
        activityCounterValue: 1,
        completedToday: false,
        goal: 10,
        goalType: GoalType.Times,
        createDate: new Date(),
        startDate: new Date(),
        currentStreak: 0,
        currentStreakStartDate: new Date(),
        completedTargets: 0,
        failedTargets: 0,
        totalTargets: 0,
        targets: targets,
    },
    {
        id: '2',
        title: 'Exercise',
        periodicity: Periodicity.Weekly,
        periodicityValue: 'Monday, Wednesday, Friday',
        activityType: ActivityType.Counter,
        activityCounterValue: 0,
        completedToday: false,
        goal: 180,
        goalType: GoalType.Mins,
        createDate: new Date(),
        startDate: new Date(),
        currentStreak: 0,
        currentStreakStartDate: new Date(),
        completedTargets: 0,
        failedTargets: 0,
        totalTargets: 0,
        targets: [],
    },
    {
        id: '3',
        title: 'Read a book',
        periodicity: Periodicity.Monthly,
        activityType: ActivityType.Boolean,
        activityCounterValue: 0,
        completedToday: false,
        goal: 2,
        goalType: GoalType.Times,
        createDate: new Date(),
        startDate: new Date(),
        currentStreak: 0,
        currentStreakStartDate: new Date(),
        completedTargets: 0,
        failedTargets: 0,
        totalTargets: 0,
        targets: [],
    },
    {
        id: '4',
        title: 'Learn a new skill',
        periodicity: Periodicity.Custom,
        periodicityValue: 'every other day',
        activityType: ActivityType.Counter,
        activityCounterValue: 0,
        completedToday: false,
        goal: 20,
        goalType: GoalType.Mins,
        createDate: new Date(),
        startDate: new Date(),
        currentStreak: 0,
        currentStreakStartDate: new Date(),
        completedTargets: 0,
        failedTargets: 0,
        totalTargets: 0,
        targets: [],
    },
    {
        id: '5',
        title: 'Practice an instrument',
        periodicity: Periodicity.Daily,
        activityType: ActivityType.Counter,
        activityCounterValue: 0,
        completedToday: false,
        goal: 30,
        goalType: GoalType.Mins,
        createDate: new Date(),
        startDate: new Date(),
        currentStreak: 0,
        currentStreakStartDate: new Date(),
        completedTargets: 0,
        totalTargets: 0,
        failedTargets: 0,
        targets: [],
    },
];
